"""Engine throttle table for the shared baseline.

    python run_engine_table.py      # writes baseline/engine_table.yaml (a few seconds)

Computes the delivered throttle line of the flight engine from
baseline/h2_baseline.yaml with the h2cea engine model (operating_line.py):
real-fluid liquid N2O card at the nominal tank state, fuel flow fixed by the
venturi, oxidizer throttled, throat sized for the rated thrust at the rated
chamber pressure, eta_cstar on c*, eta_cf_vac on the vacuum thrust coefficient.

The mission, injector and tank tools read the table instead of computing their
own engine. Re-run this script after changing the engine, propellant or tank
pressure inputs of the baseline, and commit both files together. The tools stop
with a message if the table no longer matches the baseline.
"""
import datetime as dt
import math

import yaml

from h2cea import config as C
from h2cea.operating_line import size_throat, state, thrust_to_mox
from h2cea.propellants import ethanol_card, n2o_card

import e2_baseline   # on sys.path through h2cea.config


def build(bl):
    ox = n2o_card(C.T_OX_NOM, C.P_TANK)
    fuel = ethanol_card(C.ETHANOL_WT)
    kw = dict(eps=C.EPS, mf=C.MDOT_FUEL, eta_c=C.ETA_CSTAR, eta_f=C.ETA_CF_VAC, ox=ox, fuel=fuel)
    _, At = size_throat(F=C.F_MAX, pc=C.PC_MAX, **kw)
    rows = []
    for f in bl["engine"]["throttle_points"]:
        s = state(thrust_to_mox(f * C.F_MAX, At, **kw), At, **kw)
        rows.append(dict(
            throttle=round(float(f), 4), thrust_N=round(s["F"], 1), mixture_ratio=round(s["MR"], 3),
            chamber_pressure_bar=round(s["pc"], 2), ox_flow_kg_s=round(s["mox"], 4),
            fuel_flow_kg_s=round(s["mf"], 4), total_flow_kg_s=round(s["mdot"], 4),
            isp_s=round(s["isp"], 1), cstar_m_s=round(C.ETA_CSTAR * s["cstar_ideal"], 1),
            chamber_temperature_K=round(s["Tc"], 0), exit_pressure_bar=round(s["pe"], 3),
            separation_risk=bool(s["pe"] < 0.4 * C.P_AMB)))   # Summerfield criterion
    return At, rows


def main():
    bl = C.BASELINE
    At, rows = build(bl)
    out = dict(
        meta=dict(generated_by="h2cea/run_engine_table.py", date=str(dt.date.today()),
                  baseline=e2_baseline.describe(bl),
                  status="estimate (CEA equilibrium, liquid N2O card, assumed efficiencies)"),
        throat=dict(area_mm2=round(At * 1e6, 2), diameter_mm=round(math.sqrt(4 * At / math.pi) * 1e3, 3)),
        rows=rows,
        inputs=e2_baseline.table_inputs(bl))
    path = e2_baseline.table_path(bl)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# Engine throttle table. Generated by h2cea/run_engine_table.py from h2_baseline.yaml.\n"
                 "# Do not edit by hand; re-run the script after changing the baseline.\n")
        yaml.safe_dump(out, fh, sort_keys=False)
    print(f"{'thr':>5}{'F N':>8}{'O/F':>7}{'pc bar':>8}{'ox kg/s':>9}{'tot kg/s':>9}{'Isp s':>7}{'Tc K':>7}{'pe bar':>8}")
    for r in rows:
        print(f"{r['throttle']:5.2f}{r['thrust_N']:8.0f}{r['mixture_ratio']:7.2f}{r['chamber_pressure_bar']:8.2f}"
              f"{r['ox_flow_kg_s']:9.3f}{r['total_flow_kg_s']:9.3f}{r['isp_s']:7.1f}"
              f"{r['chamber_temperature_K']:7.0f}{r['exit_pressure_bar']:8.3f}"
              + ("  separation risk" if r["separation_risk"] else ""))
    print(f"Throat diameter {out['throat']['diameter_mm']:.2f} mm -> {path}")


if __name__ == "__main__":
    main()
