"""
engine_performance.py - estimated throttle line of the E2-derived lander engine.

The fuel flow is fixed by the fuel cavitating venturi and only the oxidizer is
throttled, so every throttle point has its own mixture ratio and chamber
pressure. The throat area is fixed by the rated point (rated thrust at the
rated chamber pressure). For each throttle point the script finds the mixture
ratio at which the engine delivers the required thrust:

    m_dot   = m_dot_fuel * (1 + O/F)
    p_c     = eta_c* * c*_ideal(p_c, O/F) * m_dot / A_t        (fixed point)
    Isp     = eta_c* * eta_CF * Isp_ideal,ambient(p_c, O/F, eps, p_amb)
    F       = m_dot * g0 * Isp

Ideal values come from NASA CEA via RocketCEA (equilibrium, sea-level ambient
pressure term included). The result is an estimate until eta_c* and eta_CF are
measured in E2-C1.

Reads the `engine` section of h2_mission_inputs.yaml and writes
engine_performance.yaml, which mission_sizing.py reads.

    python engine_performance.py [--inputs h2_mission_inputs.yaml]
"""
from __future__ import annotations

import argparse
import datetime as dt
from pathlib import Path

import yaml
from rocketcea.cea_obj_w_units import CEA_Obj

G0 = 9.80665


def build_table(e):
    cea = CEA_Obj(oxName=e["oxidizer"], fuelName=e["fuel"], pressure_units="bar",
                  isp_units="sec", cstar_units="m/s", temperature_units="K")
    mf, eps, pa = e["fuel_flow_kg_s"], e["expansion_ratio"], e["ambient_pressure_bar"]
    eta_c, eta_f = e["eta_cstar"], e["eta_cf"]

    def isp_del(pc, mr):
        return eta_c * eta_f * float(cea.estimate_Ambient_Isp(Pc=pc, MR=mr, eps=eps, Pamb=pa)[0])

    def bisect(fun, lo, hi, n=60):
        flo = fun(lo)
        for _ in range(n):
            mid = 0.5 * (lo + hi)
            fm = fun(mid)
            if (fm > 0) == (flo > 0):
                lo, flo = mid, fm
            else:
                hi = mid
        return 0.5 * (lo + hi)

    # Rated point: known thrust and chamber pressure -> O/F and throat area
    pc_r, F_r = e["chamber_pressure_rated_bar"], e["rated_thrust_N"]
    mr_r = bisect(lambda mr: mf * (1 + mr) * G0 * isp_del(pc_r, mr) - F_r, 1.0, 8.0)
    md_r = mf * (1 + mr_r)
    A_t = eta_c * float(cea.get_Cstar(Pc=pc_r, MR=mr_r)) * md_r / (pc_r * 1e5)

    def chamber(mr):
        md, pc = mf * (1 + mr), pc_r
        for _ in range(30):
            pc_new = eta_c * float(cea.get_Cstar(Pc=pc, MR=mr)) * md / A_t / 1e5
            if abs(pc_new - pc) < 1e-6:
                break
            pc = pc_new
        return md, pc

    rows = []
    for f in e["throttle_points"]:
        target = f * F_r
        mr = bisect(lambda m: (lambda md, pc: md * G0 * isp_del(pc, m))(*chamber(m)) - target, 0.8, 8.0)
        md, pc = chamber(mr)
        isp = isp_del(pc, mr)
        pe = pc / float(cea.get_PcOvPe(Pc=pc, MR=mr, eps=eps))
        rows.append(dict(
            throttle=round(f, 4), thrust_N=round(md * G0 * isp, 1), mixture_ratio=round(mr, 3),
            chamber_pressure_bar=round(pc, 2), ox_flow_kg_s=round(md - mf, 4),
            fuel_flow_kg_s=round(mf, 4), total_flow_kg_s=round(md, 4), isp_s=round(isp, 1),
            cstar_m_s=round(eta_c * float(cea.get_Cstar(Pc=pc, MR=mr)), 1),
            chamber_temperature_K=round(float(cea.get_Tcomb(Pc=pc, MR=mr)), 0),
            exit_pressure_bar=round(pe, 3),
            separation_risk=bool(pe < 0.4 * pa)))  # Summerfield criterion
    return A_t, rows


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--inputs", default="h2_mission_inputs.yaml")
    a = ap.parse_args()
    path = Path(a.inputs)
    cfg = yaml.safe_load(path.read_text())
    e = cfg["engine"]
    A_t, rows = build_table(e)
    out = dict(
        meta=dict(generated_by="engine_performance.py", date=str(dt.date.today()),
                  status="estimate (CEA equilibrium x assumed efficiencies)",
                  inputs=str(path.name)),
        basis=dict(oxidizer=e["oxidizer"], fuel=e["fuel"], fuel_flow_kg_s=e["fuel_flow_kg_s"],
                   rated_thrust_N=e["rated_thrust_N"],
                   chamber_pressure_rated_bar=e["chamber_pressure_rated_bar"],
                   expansion_ratio=e["expansion_ratio"], ambient_pressure_bar=e["ambient_pressure_bar"],
                   eta_cstar=e["eta_cstar"], eta_cf=e["eta_cf"],
                   throat_area_mm2=round(A_t * 1e6, 1),
                   throat_diameter_mm=round((4 * A_t / 3.141592653589793) ** 0.5 * 1e3, 2)),
        table=rows)
    out_path = path.parent / e.get("performance_file", "engine_performance.yaml")
    with open(out_path, "w") as fh:
        fh.write("# Estimated E2 lander throttle line. Generated by engine_performance.py, do not edit by hand.\n")
        yaml.safe_dump(out, fh, sort_keys=False)
    print(f"{'thr':>5}{'F N':>8}{'O/F':>7}{'pc bar':>8}{'ox kg/s':>9}{'tot kg/s':>9}{'Isp s':>7}{'Tc K':>7}{'pe bar':>8}")
    for r in rows:
        print(f"{r['throttle']:5.2f}{r['thrust_N']:8.0f}{r['mixture_ratio']:7.2f}{r['chamber_pressure_bar']:8.2f}"
              f"{r['ox_flow_kg_s']:9.3f}{r['total_flow_kg_s']:9.3f}{r['isp_s']:7.1f}"
              f"{r['chamber_temperature_K']:7.0f}{r['exit_pressure_bar']:8.3f}"
              + ("  separation risk" if r["separation_risk"] else ""))
    print(f"Throat diameter {out['basis']['throat_diameter_mm']} mm -> {out_path}")


if __name__ == "__main__":
    main()
